# Generated by Django 4.2.7 on 2024-03-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='height',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AddField(
            model_name='note',
            name='width',
            field=models.IntegerField(blank=True, default=10),
        ),
    ]
