# Generated by Django 4.2.7 on 2024-03-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0002_note_height_note_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='height',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='note',
            name='width',
            field=models.CharField(max_length=255),
        ),
    ]
